openapi: 3.0.0
info:
  title: Query API
  version: 1.0.0
servers:
  - url: http://localhost:8145
paths:
  /_query:
    $ref: './paths/query.yaml'
  /-/health:
    $ref: './paths/health.yaml'
  /-/info:
    $ref: './paths/info.yaml'
  /-/ready:
    $ref: './paths/ready.yaml'
components:
  schemas:
    $ref: './schemas/_index.yaml'

