#!/bin/bash
set -eu

# Create the directory
mkdir -p /var/run/env

# Set umask for proper permissions
umask 022

# Write the environment JavaScript file
cat > /var/run/env/env.js << 'EOF'
// Generated by docker-compose env-writer
window.__ENV__ = {
  GQ_API_BASE_URL: "${GQ_API_BASE_URL}",
  HOST_RESOLVER_TYPES: "${HOST_RESOLVER_TYPES}",
  SSE_ON_LOAD: "${SSE_ON_LOAD}"
};
EOF

# Substitute environment variables
sed -i "s|\${GQ_API_BASE_URL}|${GQ_API_BASE_URL:-/api}|g" /var/run/env/env.js
sed -i "s|\${HOST_RESOLVER_TYPES}|${HOST_RESOLVER_TYPES:-string}|g" /var/run/env/env.js
sed -i "s|\${SSE_ON_LOAD}|${SSE_ON_LOAD:-true}|g" /var/run/env/env.js

# Set proper file permissions for caddy user (uid:gid 1001:1001)
chown 1001:1001 /var/run/env/env.js
chmod 644 /var/run/env/env.js

echo "Environment file created successfully at /var/run/env/env.js"
