#!/bin/sh
set -eu

mkdir -p /var/run/env
umask 022

# Write a literal template; envsubst will replace only the listed variables.
# Using envsubst (from gettext) is safe with URL values that contain characters
# that would break sed delimiters (e.g. '|', '/', '&').
cat > /tmp/env.js.tmpl << 'TMPL'
// Generated by docker-compose env-writer
window.__ENV__ = {
  GQ_API_BASE_URL: "${GQ_API_BASE_URL}",
  HOST_RESOLVER_TYPES: "${HOST_RESOLVER_TYPES}",
  SSE_ON_LOAD: "${SSE_ON_LOAD}"
};
TMPL

# Substitute only the three known variables; leave any other ${...} untouched.
GQ_API_BASE_URL="${GQ_API_BASE_URL:-}" \
  HOST_RESOLVER_TYPES="${HOST_RESOLVER_TYPES:-string}" \
  SSE_ON_LOAD="${SSE_ON_LOAD:-true}" \
  envsubst '$GQ_API_BASE_URL $HOST_RESOLVER_TYPES $SSE_ON_LOAD' \
  < /tmp/env.js.tmpl > /var/run/env/env.js

# Set proper file permissions for caddy user (uid:gid 1001:1001)
chown 1001:1001 /var/run/env/env.js
chmod 644 /var/run/env/env.js

echo "Environment file created successfully at /var/run/env/env.js"
