//go:build ignore && goprobe_contrib

package main

import (
	"os"
)

const contribImport = `//go:build goprobe_contrib

// Code generated by gen.go - DO NOT EDIT.
package contrib

import _ "github.com/fako1024/goProbe-contrib"
`

func main() {
	os.WriteFile("contrib_generated.go", []byte(contribImport), 0644)
}
