const path = require("path");
const fs = require("fs");
const webpack = require("webpack");
const dotenv = require("dotenv");
const HtmlWebpackPlugin = require("html-webpack-plugin");
const MiniCssExtractPlugin = require("mini-css-extract-plugin");

const mode =
  process.env.NODE_ENV === "production" ? "production" : "development";
const envFile = `.env.${mode}`;
const envPath = path.resolve(__dirname, envFile);
if (fs.existsSync(envPath)) {
  dotenv.config({ path: envPath });
}

// Backend API origin used only for the dev proxy (not baked into the bundle).
// The runtime env.js / window.__ENV__ is the source of truth for the browser.
const GQ_API_BASE_URL =
  process.env.GQ_API_BASE_URL || "http://localhost:8145";

module.exports = {
  context: __dirname,
  mode,
  entry: path.resolve(__dirname, "src/index.tsx"),
  output: {
    path: path.resolve(__dirname, "dist"),
    filename: "bundle.js",
    publicPath: "/",
    clean: true,
  },
  resolve: {
    extensions: [".tsx", ".ts", ".js"],
  },
  module: {
    rules: [
      {
        test: /\.tsx?$/,
        use: [
          {
            loader: "ts-loader",
            options: {
              transpileOnly: true,
              configFile: path.resolve(__dirname, "tsconfig.json"),
            },
          },
        ],
        exclude: /node_modules/,
      },
      {
        test: /\.css$/,
        use: [
          // Extract CSS to a file in production; inject via <style> in dev for HMR
          mode === "production" ? MiniCssExtractPlugin.loader : "style-loader",
          {
            loader: "css-loader",
            options: { importLoaders: 1 },
          },
          "postcss-loader",
        ],
      },
    ],
  },
  plugins: [
    new webpack.DefinePlugin({
      "process.env.NODE_ENV": JSON.stringify(mode),
    }),
    new HtmlWebpackPlugin({
      template: path.resolve(__dirname, "index.html"),
      inject: "body",
      scriptLoading: "defer",
      filename: "index.html",
    }),
    ...(mode === "production"
      ? [new MiniCssExtractPlugin({ filename: "styles.css" })]
      : []),
  ],
  devtool: mode === "production" ? "source-map" : "eval-source-map",
  stats: "minimal",
  devServer: {
    host: "0.0.0.0",
    port: 5173,
    static: false,
    hot: true,
    historyApiFallback: true,
    client: { overlay: true },
    allowedHosts: "all",
    // Proxy API requests to the backend so the dev server and backend share
    // the same origin from the browser's perspective — no CORS needed in dev.
    proxy: [
      {
        context: ["/_query", "/-/"],
        target: GQ_API_BASE_URL,
        changeOrigin: true,
      },
    ],
    setupMiddlewares: (middlewares, devServer) => {
      if (!devServer) return middlewares;
      const app = devServer.app;
      // Serve /env.js at runtime so the browser reads the same variables
      // as the backend proxy target, matching production Caddy behaviour.
      app.get("/env.js", (_req, res) => {
        // Use ?? (not ||) so an empty string is preserved: empty GQ_API_BASE_URL
        // means the browser uses relative paths, which the proxy forwards to the backend.
        const gq = process.env.GQ_API_BASE_URL ?? "";
        const types = process.env.HOST_RESOLVER_TYPES ?? "string";
        const sse = String(process.env.SSE_ON_LOAD ?? "true");
        res.setHeader("Content-Type", "application/javascript; charset=utf-8");
        res.end(
          `// Generated by webpack-dev-server\nwindow.__ENV__ = {\n  GQ_API_BASE_URL: ${JSON.stringify(gq)},\n  HOST_RESOLVER_TYPES: ${JSON.stringify(types)},\n  SSE_ON_LOAD: ${JSON.stringify(sse)}\n};\n`,
        );
      });
      return middlewares;
    },
  },
};
