
// Code generated by 'go run make_version.go'. DO NOT EDIT.
package version
import (
    "fmt"
    "time"
)
func init() {
    var err error
    BuildTime, err = time.Parse(time.UnixDate, "Sun May 19 09:09:28 UTC 2019")
    if err != nil {
        panic(err)
    }
    GitSHA = fmt.Sprintf("%s", "v3.0.0+29a052c9991466fd4bda0b7c3c2b21a0c8833534")
}
