type: object
allOf:
  - $ref: './response.yaml'
properties:
  enabled:
    type: array
    items:
      type: object
      additionalProperties:
        $ref: './IfaceChange.yaml'
    description: Interfaces that were enabled.
    example:
      - IfaceChange:
        name: "eth0"
        success: true
      - IfaceChange:
        name: "eth1"
        success: false
  updated:
    type: array
    items:
      type: object
      additionalProperties:
        $ref: './IfaceChange.yaml'
    description: Interfaces that were updated.
    example:
      - IfaceChange:
        name: "eth2"
        success: true
  disabled:
    type: array
    items:
      type: object
      additionalProperties:
        $ref: './IfaceChange.yaml'
    description: Interfaces that were disabled.
    example:
      - IfaceChange:
        name: "eth5"
        success: true
      - IfaceChange:
        name: "eth6"
        success: false
